"""
Constants for the ARCANOS CLI runtime configuration.
"""

DEFAULT_ACTIVITY_HISTORY_LIMIT = 200
DEFAULT_HEARTBEAT_INTERVAL_SECONDS = 60
DEFAULT_COMMAND_POLL_INTERVAL_SECONDS = 30
DEFAULT_DEBUG_SERVER_PORT = 9999
MIN_REGISTRY_CACHE_TTL_MINUTES = 1
DEFAULT_QUEUED_ACTIONS_COUNT = 0
SINGLE_ACTION_COUNT = 1
ZERO_COST_USD = 0.0
ZERO_TOKENS_USED = 0