"""
Constants for the ARCANOS CLI runtime configuration.
"""

DEFAULT_ACTIVITY_HISTORY_LIMIT = 200
DEFAULT_HEARTBEAT_INTERVAL_SECONDS = 60
DEFAULT_COMMAND_POLL_INTERVAL_SECONDS = 30
DEFAULT_DEBUG_SERVER_PORT = 9999
MIN_REGISTRY_CACHE_TTL_MINUTES = 1
