// Generated by clients/ios/scripts/derive-gateway-contract.mjs. Do not edit.
// Source: src/services/gptAccessGateway.ts, buildGptAccessOpenApiDocument.
// JSON schemas remain authoritative for validation; these are transport DTOs.

import Foundation

public struct ConfirmationChallenge: Codable, Equatable, Sendable {
    public let id: String
    public let issuedAt: String?
    public let expiresAt: String?
    public let ttlMs: Int?
    public let instructions: [String]?
    public let gptIdTrusted: Bool?
    public let allowedGptIds: [String]?
    public let providedTokenStatus: String?

    public init(id: String, issuedAt: String? = nil, expiresAt: String? = nil, ttlMs: Int? = nil, instructions: [String]? = nil, gptIdTrusted: Bool? = nil, allowedGptIds: [String]? = nil, providedTokenStatus: String? = nil) {
        self.id = id
        self.issuedAt = issuedAt
        self.expiresAt = expiresAt
        self.ttlMs = ttlMs
        self.instructions = instructions
        self.gptIdTrusted = gptIdTrusted
        self.allowedGptIds = allowedGptIds
        self.providedTokenStatus = providedTokenStatus
    }
}

public struct ConfirmationRequiredResponse: Codable, Equatable, Sendable {
    public let error: String?
    public let message: String?
    public let code: String
    public let endpoint: String?
    public let method: String?
    public let gptId: String?
    public let confirmationRequired: Bool
    public let confirmationStatus: String?
    public let confirmationChallenge: ConfirmationChallenge
    public let timestamp: String?

    public init(error: String? = nil, message: String? = nil, code: String, endpoint: String? = nil, method: String? = nil, gptId: String? = nil, confirmationRequired: Bool, confirmationStatus: String? = nil, confirmationChallenge: ConfirmationChallenge, timestamp: String? = nil) {
        self.error = error
        self.message = message
        self.code = code
        self.endpoint = endpoint
        self.method = method
        self.gptId = gptId
        self.confirmationRequired = confirmationRequired
        self.confirmationStatus = confirmationStatus
        self.confirmationChallenge = confirmationChallenge
        self.timestamp = timestamp
    }
}

public struct ErrorResponse: Codable, Equatable, Sendable {
    public let ok: Bool
    public let status: String?
    public let service: String?
    public let traceId: String?
    public let error: ErrorResponseError

    public init(ok: Bool, status: String? = nil, service: String? = nil, traceId: String? = nil, error: ErrorResponseError) {
        self.ok = ok
        self.status = status
        self.service = service
        self.traceId = traceId
        self.error = error
    }
}

public struct ErrorResponseError: Codable, Equatable, Sendable {
    public let code: String
    public let message: String

    public init(code: String, message: String) {
        self.code = code
        self.message = message
    }
}

public struct CreateAiJobRequest: Codable, Equatable, Sendable {
    public let gptId: String
    public let task: String
    public let input: [String: JSONValue]?
    public let context: String?
    public let maxOutputTokens: Int?
    public let idempotencyKey: String?

    public init(gptId: String, task: String, input: [String: JSONValue]? = nil, context: String? = nil, maxOutputTokens: Int? = nil, idempotencyKey: String? = nil) {
        self.gptId = gptId
        self.task = task
        self.input = input
        self.context = context
        self.maxOutputTokens = maxOutputTokens
        self.idempotencyKey = idempotencyKey
    }
}

public struct CreateAiJobResponse: Codable, Equatable, Sendable {
    public let ok: Bool
    public let jobId: String
    public let traceId: String
    public let status: String
    public let deduped: Bool
    public let resultEndpoint: String

    public init(ok: Bool, jobId: String, traceId: String, status: String, deduped: Bool, resultEndpoint: String) {
        self.ok = ok
        self.jobId = jobId
        self.traceId = traceId
        self.status = status
        self.deduped = deduped
        self.resultEndpoint = resultEndpoint
    }
}

public struct JobResultRequest: Codable, Equatable, Sendable {
    public let jobId: String
    public let traceId: String?

    public init(jobId: String, traceId: String? = nil) {
        self.jobId = jobId
        self.traceId = traceId
    }
}

public struct JobResultError: Codable, Equatable, Sendable {
    public let code: String
    public let message: String
    public let details: [String: JSONValue]?

    public init(code: String, message: String, details: [String: JSONValue]? = nil) {
        self.code = code
        self.message = message
        self.details = details
    }
}

public struct JobResultResponse: Codable, Equatable, Sendable {
    public let ok: Bool
    public let traceId: String?
    public let jobId: String
    public let status: String
    public let jobStatus: String?
    public let lifecycleStatus: String
    public let createdAt: String?
    public let updatedAt: String?
    public let completedAt: String?
    public let retentionUntil: String?
    public let idempotencyUntil: String?
    public let expiresAt: String?
    public let poll: String
    public let stream: String
    public let resultEndpoint: String
    public let result: JSONValue
    public let error: JobResultError?

    public init(ok: Bool, traceId: String? = nil, jobId: String, status: String, jobStatus: String? = nil, lifecycleStatus: String, createdAt: String? = nil, updatedAt: String? = nil, completedAt: String? = nil, retentionUntil: String? = nil, idempotencyUntil: String? = nil, expiresAt: String? = nil, poll: String, stream: String, resultEndpoint: String, result: JSONValue, error: JobResultError? = nil) {
        self.ok = ok
        self.traceId = traceId
        self.jobId = jobId
        self.status = status
        self.jobStatus = jobStatus
        self.lifecycleStatus = lifecycleStatus
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.completedAt = completedAt
        self.retentionUntil = retentionUntil
        self.idempotencyUntil = idempotencyUntil
        self.expiresAt = expiresAt
        self.poll = poll
        self.stream = stream
        self.resultEndpoint = resultEndpoint
        self.result = result
        self.error = error
    }
}

public struct CapabilityV1Summary: Codable, Equatable, Sendable {
    public let id: String
    public let description: String?
    public let route: String?
    public let actions: [String]
    public let enabled: Bool?

    public init(id: String, description: String? = nil, route: String? = nil, actions: [String], enabled: Bool? = nil) {
        self.id = id
        self.description = description
        self.route = route
        self.actions = actions
        self.enabled = enabled
    }
}

public struct CapabilityV1Detail: Codable, Equatable, Sendable {
    public let id: String
    public let name: String
    public let description: String?
    public let route: String?
    public let actions: [String]
    public let enabled: Bool?
    public let actionMetadata: [String: CapabilityV1DetailActionMetadataValue]?
    public let defaultAction: String?
    public let defaultTimeoutMs: Int?

    public init(id: String, name: String, description: String? = nil, route: String? = nil, actions: [String], enabled: Bool? = nil, actionMetadata: [String: CapabilityV1DetailActionMetadataValue]? = nil, defaultAction: String? = nil, defaultTimeoutMs: Int? = nil) {
        self.id = id
        self.name = name
        self.description = description
        self.route = route
        self.actions = actions
        self.enabled = enabled
        self.actionMetadata = actionMetadata
        self.defaultAction = defaultAction
        self.defaultTimeoutMs = defaultTimeoutMs
    }
}

public struct CapabilityV1DetailActionMetadataValue: Codable, Equatable, Sendable {
    public let description: String?
    public let risk: String
    public let requiresConfirmation: Bool
    public let inputSchema: [String: JSONValue]?
    public let outputSchema: [String: JSONValue]?
    public let idempotent: Bool?
    public let executionTarget: String?
    public let timeoutMs: Int?
    public let requiredDeviceScopes: [String]?
    public let readOnly: Bool?
    public let mayModifyFiles: Bool?

    public init(description: String? = nil, risk: String, requiresConfirmation: Bool, inputSchema: [String: JSONValue]? = nil, outputSchema: [String: JSONValue]? = nil, idempotent: Bool? = nil, executionTarget: String? = nil, timeoutMs: Int? = nil, requiredDeviceScopes: [String]? = nil, readOnly: Bool? = nil, mayModifyFiles: Bool? = nil) {
        self.description = description
        self.risk = risk
        self.requiresConfirmation = requiresConfirmation
        self.inputSchema = inputSchema
        self.outputSchema = outputSchema
        self.idempotent = idempotent
        self.executionTarget = executionTarget
        self.timeoutMs = timeoutMs
        self.requiredDeviceScopes = requiredDeviceScopes
        self.readOnly = readOnly
        self.mayModifyFiles = mayModifyFiles
    }
}

public struct CapabilitiesV1Response: Codable, Equatable, Sendable {
    public let ok: Bool
    public let capabilities: [CapabilityV1Summary]

    public init(ok: Bool, capabilities: [CapabilityV1Summary]) {
        self.ok = ok
        self.capabilities = capabilities
    }
}

public struct CapabilityV1DetailResponse: Codable, Equatable, Sendable {
    public let ok: Bool
    public let exists: Bool
    public let capability: CapabilityV1Detail?

    public init(ok: Bool, exists: Bool, capability: CapabilityV1Detail? = nil) {
        self.ok = ok
        self.exists = exists
        self.capability = capability
    }
}

public struct CapabilityRunRequest: Codable, Equatable, Sendable {
    public let action: String
    public let payload: JSONValue?
    public let confirmationToken: String?

    public init(action: String, payload: JSONValue? = nil, confirmationToken: String? = nil) {
        self.action = action
        self.payload = payload
        self.confirmationToken = confirmationToken
    }

    enum CodingKeys: String, CodingKey {
        case action
        case payload
        case confirmationToken = "confirmation_token"
    }
}

public struct CapabilityRunResponse: Codable, Equatable, Sendable {
    public let ok: Bool
    public let result: JSONValue

    public init(ok: Bool, result: JSONValue) {
        self.ok = ok
        self.result = result
    }
}

public struct DevicePairingRequest: Codable, Equatable, Sendable {
    public let scopes: [String]?
    public let capabilityActions: [String]?

    public init(scopes: [String]? = nil, capabilityActions: [String]? = nil) {
        self.scopes = scopes
        self.capabilityActions = capabilityActions
    }
}

public struct DevicePairingResponse: Codable, Equatable, Sendable, CustomStringConvertible, CustomDebugStringConvertible {
    public let ok: Bool
    public let pairingToken: String
    public let expiresAt: String
    public let origin: String

    public init(ok: Bool, pairingToken: String, expiresAt: String, origin: String) {
        self.ok = ok
        self.pairingToken = pairingToken
        self.expiresAt = expiresAt
        self.origin = origin
    }

    public var description: String { "DevicePairingResponse(<redacted>)" }
    public var debugDescription: String { description }
}

public struct DevicePairRequest: Codable, Equatable, Sendable, CustomStringConvertible, CustomDebugStringConvertible {
    public let pairingToken: String
    public let localIdentity: String

    public init(pairingToken: String, localIdentity: String) {
        self.pairingToken = pairingToken
        self.localIdentity = localIdentity
    }

    public var description: String { "DevicePairRequest(<redacted>)" }
    public var debugDescription: String { description }
}

public struct DeviceCredentialResponse: Codable, Equatable, Sendable, CustomStringConvertible, CustomDebugStringConvertible {
    public let ok: Bool
    public let deviceId: String
    public let credential: String
    public let tokenType: String
    public let audience: String
    public let origin: String
    public let issuedAt: String
    public let expiresAt: String
    public let renewalExpiresAt: String
    public let scopes: [String]
    public let capabilityActions: [String]
    public let gptIds: [String]

    public init(ok: Bool, deviceId: String, credential: String, tokenType: String, audience: String, origin: String, issuedAt: String, expiresAt: String, renewalExpiresAt: String, scopes: [String], capabilityActions: [String], gptIds: [String]) {
        self.ok = ok
        self.deviceId = deviceId
        self.credential = credential
        self.tokenType = tokenType
        self.audience = audience
        self.origin = origin
        self.issuedAt = issuedAt
        self.expiresAt = expiresAt
        self.renewalExpiresAt = renewalExpiresAt
        self.scopes = scopes
        self.capabilityActions = capabilityActions
        self.gptIds = gptIds
    }

    public var description: String { "DeviceCredentialResponse(<redacted>)" }
    public var debugDescription: String { description }
}

public struct DeviceSessionResponse: Codable, Equatable, Sendable {
    public let ok: Bool
    public let deviceId: String
    public let tokenType: String
    public let audience: String
    public let origin: String
    public let issuedAt: String
    public let expiresAt: String
    public let renewalExpiresAt: String
    public let scopes: [String]
    public let capabilityActions: [String]
    public let gptIds: [String]
    public let state: String

    public init(ok: Bool, deviceId: String, tokenType: String, audience: String, origin: String, issuedAt: String, expiresAt: String, renewalExpiresAt: String, scopes: [String], capabilityActions: [String], gptIds: [String], state: String) {
        self.ok = ok
        self.deviceId = deviceId
        self.tokenType = tokenType
        self.audience = audience
        self.origin = origin
        self.issuedAt = issuedAt
        self.expiresAt = expiresAt
        self.renewalExpiresAt = renewalExpiresAt
        self.scopes = scopes
        self.capabilityActions = capabilityActions
        self.gptIds = gptIds
        self.state = state
    }
}

public struct DeviceRenewRequest: Codable, Equatable, Sendable {


    public init() {

    }
}

public struct DeviceRevokeRequest: Codable, Equatable, Sendable {


    public init() {

    }
}

public struct DeviceRevokeResponse: Codable, Equatable, Sendable {
    public let ok: Bool
    public let deviceId: String
    public let state: String

    public init(ok: Bool, deviceId: String, state: String) {
        self.ok = ok
        self.deviceId = deviceId
        self.state = state
    }
}

public typealias CreateAIJobRequest = CreateAiJobRequest
public typealias CreateAIJobResponse = CreateAiJobResponse
