import { jest } from "@jest/globals";

const dispatchProtocolRequestMock = jest.fn();

jest.unstable_mockModule("../src/transport.js", () => ({
  dispatchProtocolRequest: dispatchProtocolRequestMock
}));

const { invokeTool } = await import("../src/client.js");

describe("CLI tool client", () => {
  beforeEach(() => {
    jest.restoreAllMocks();
    dispatchProtocolRequestMock.mockReset();
  });

  it("fails early with a friendly message when local transport is explicitly requested for tool.invoke", async () => {
    await expect(
      invokeTool({
        toolId: "doctor.implementation",
        inputs: {},
        transport: "local",
        transportExplicit: true
      })
    ).rejects.toThrow(
      'Protocol command "tool.invoke" requires the python transport'
    );
  });

  it("uses the same autogenerated request id for semantically identical tool inputs", async () => {
    dispatchProtocolRequestMock.mockResolvedValue({
      protocol: "arcanos-v1",
      requestId: "req-mocked",
      ok: true,
      data: {
        result: {
          status: "ok"
        }
      },
      meta: {
        version: "0.1.0",
        executedBy: "jest"
      }
    });

    await invokeTool({
      toolId: "repo.readFile",
      inputs: {
        path: "README.md",
        line: 12
      }
    });

    await invokeTool({
      toolId: "repo.readFile",
      inputs: {
        line: 12,
        path: "README.md"
      }
    });

    const [firstRequest] = dispatchProtocolRequestMock.mock.calls[0] ?? [];
    const [secondRequest] = dispatchProtocolRequestMock.mock.calls[1] ?? [];

    expect(firstRequest?.requestId).toBeDefined();
    expect(firstRequest?.requestId).toBe(secondRequest?.requestId);
  });
});
