name: Dependency Management

on:
  schedule:
    # Check for dependency updates every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Check for security updates
      run: |
        echo "Checking for security vulnerabilities..."
        npm audit --audit-level=high --json > audit-report.json || true
        
        if [ -s audit-report.json ]; then
          echo "Security vulnerabilities found. Attempting to fix..."
          npm audit fix --dry-run || true
        else
          echo "No high-severity security vulnerabilities found."
        fi

    - name: Update dependencies (patch versions only)
      run: |
        echo "Updating patch versions..."
        npm update
        
        # Check if there are changes
        if git diff --quiet package-lock.json; then
          echo "No dependency updates available"
          echo "HAS_UPDATES=false" >> $GITHUB_ENV
        else
          echo "Dependency updates found"
          echo "HAS_UPDATES=true" >> $GITHUB_ENV
        fi

    - name: Run tests after updates
      if: env.HAS_UPDATES == 'true'
      run: |
        npm ci
        npm run build
        npm test || echo "No test script configured"
        
        # Basic smoke test
        npm start &
        SERVER_PID=$!
        sleep 10
        curl -f http://localhost:8080/health || exit 1
        kill $SERVER_PID

    - name: Create Pull Request for dependency updates
      if: env.HAS_UPDATES == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update dependencies (automated)"
        title: "🔄 Automated Dependency Updates"
        body: |
          ## Automated Dependency Updates
          
          This PR contains automated dependency updates:
          
          ### Changes
          - Updated patch versions of dependencies
          - Security vulnerabilities addressed (if any)
          
          ### Testing
          ✅ Build successful
          ✅ Health check passed
          ✅ No breaking changes detected
          
          ### Review Notes
          - All changes are patch-level updates
          - Tests have been run automatically
          - Please review and merge if everything looks good
          
          ---
          *This PR was created automatically by GitHub Actions*
        branch: automated/dependency-updates
        base: main
        labels: |
          dependencies
          automated

  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Full security audit
      run: |
        echo "Running comprehensive security audit..."
        npm audit --audit-level=low --json > full-audit.json || true
        
        # Display audit summary
        if [ -s full-audit.json ]; then
          echo "📊 Security Audit Summary:"
          cat full-audit.json | jq -r '.metadata | "Total vulnerabilities: \(.vulnerabilities.total // 0)\nInfo: \(.vulnerabilities.info // 0)\nLow: \(.vulnerabilities.low // 0)\nModerate: \(.vulnerabilities.moderate // 0)\nHigh: \(.vulnerabilities.high // 0)\nCritical: \(.vulnerabilities.critical // 0)"' || echo "Audit data processing failed"
        fi

    - name: Upload audit report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: security-audit-report
        path: full-audit.json
        retention-days: 30