name: Patch TypeScript Build

on:
  workflow_dispatch:

jobs:
  fix-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install JSON tool
        run: npm install -g json

      - name: Patch tsconfig and scripts
        run: |
          cat > tsconfig.json << 'EOF'
          {
            "compilerOptions": {
              "target": "ES2019",
              "module": "commonjs",
              "rootDir": "src",
              "outDir": "dist",
              "strict": true,
              "esModuleInterop": true,
              "skipLibCheck": true
            },
            "include": ["src"],
            "exclude": ["node_modules", "dist"]
          }
          EOF

          npx json -I -f package.json \
            -e 'this.scripts={build:"tsc",start:"node dist/index.js",dev:"ts-node src/index.ts"}'

      - name: Commit & Push
        run: |
          git config user.name "arcanos-bot"
          git config user.email "actions@github.com"
          git add tsconfig.json package.json
          git commit -m "fix: setup TypeScript build + start scripts"
          git push