name: Health & Monitoring

on:
  schedule:
    # Check application health every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Railway deployment health
      run: |
        HEALTH_URL="${{ secrets.RAILWAY_DOMAIN }}/health"
        echo "Checking application health at: $HEALTH_URL"
        
        if [ -z "${{ secrets.RAILWAY_DOMAIN }}" ]; then
          echo "⚠️ RAILWAY_DOMAIN not configured in secrets"
          echo "Please add your Railway domain to repository secrets"
          exit 0
        fi
        
        # Perform health check with detailed output
        START_TIME=$(date +%s)
        
        if curl -f -s "$HEALTH_URL" -o health_response.json; then
          END_TIME=$(date +%s)
          RESPONSE_TIME=$((END_TIME - START_TIME))
          
          echo "✅ Health check passed!"
          echo "📊 Response time: ${RESPONSE_TIME}s"
          echo "📋 Response:"
          cat health_response.json | jq . || cat health_response.json
        else
          echo "❌ Health check failed!"
          echo "Application may be down or experiencing issues"
          exit 1
        fi

    - name: Check API endpoints
      run: |
        if [ -z "${{ secrets.RAILWAY_DOMAIN }}" ]; then
          echo "Skipping API tests - RAILWAY_DOMAIN not configured"
          exit 0
        fi
        
        BASE_URL="${{ secrets.RAILWAY_DOMAIN }}"
        
        echo "Testing API endpoints..."
        
        # Test root endpoint
        echo "Testing root endpoint..."
        curl -f "$BASE_URL/" || echo "Root endpoint test failed"
        
        # Test echo endpoint
        echo "Testing echo endpoint..."
        curl -X POST "$BASE_URL/api/echo" \
          -H "Content-Type: application/json" \
          -d '{"message":"health check test"}' || echo "Echo endpoint test failed"

    - name: Performance check
      run: |
        if [ -z "${{ secrets.RAILWAY_DOMAIN }}" ]; then
          echo "Skipping performance tests - RAILWAY_DOMAIN not configured"
          exit 0
        fi
        
        echo "Running basic performance checks..."
        
        # Test response times
        HEALTH_URL="${{ secrets.RAILWAY_DOMAIN }}/health"
        
        echo "Measuring response times (5 requests)..."
        for i in {1..5}; do
          START=$(date +%s%N)
          curl -f -s "$HEALTH_URL" > /dev/null
          END=$(date +%s%N)
          DURATION=$(((END - START) / 1000000))
          echo "Request $i: ${DURATION}ms"
        done

  uptime-monitoring:
    runs-on: ubuntu-latest
    
    steps:
    - name: Record uptime metrics
      run: |
        echo "🕐 Uptime check at: $(date -u)"
        
        if [ -z "${{ secrets.RAILWAY_DOMAIN }}" ]; then
          echo "⚠️ RAILWAY_DOMAIN not configured - cannot perform uptime monitoring"
          echo "To enable monitoring, add your Railway domain to repository secrets"
          exit 0
        fi
        
        HEALTH_URL="${{ secrets.RAILWAY_DOMAIN }}/health"
        
        # Try to get uptime from health endpoint
        if curl -f -s "$HEALTH_URL" | jq -r '.uptime' 2>/dev/null; then
          echo "📊 Application uptime retrieved successfully"
        else
          echo "⚠️ Could not retrieve uptime metrics"
        fi

    - name: Create uptime report
      run: |
        echo "## 📊 Uptime Report" > uptime-report.md
        echo "Generated at: $(date -u)" >> uptime-report.md
        echo "" >> uptime-report.md
        
        if [ -z "${{ secrets.RAILWAY_DOMAIN }}" ]; then
          echo "⚠️ **Configuration Required**" >> uptime-report.md
          echo "Add RAILWAY_DOMAIN to repository secrets to enable monitoring" >> uptime-report.md
        else
          echo "✅ **Service Status**: Monitoring Active" >> uptime-report.md
          echo "🔗 **Health Endpoint**: ${{ secrets.RAILWAY_DOMAIN }}/health" >> uptime-report.md
        fi
        
        echo "" >> uptime-report.md
        echo "---" >> uptime-report.md
        echo "*Report generated by GitHub Actions*" >> uptime-report.md

    - name: Upload uptime report
      uses: actions/upload-artifact@v4
      with:
        name: uptime-report-$(date +%Y%m%d%H%M)
        path: uptime-report.md
        retention-days: 7

  deployment-status:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check deployment status
      run: |
        echo "🚀 Checking deployment status..."
        
        # Basic environment validation
        echo "📋 Environment Information:"
        echo "- Repository: ${{ github.repository }}"
        echo "- Branch: ${{ github.ref_name }}"
        echo "- Commit: ${{ github.sha }}"
        echo "- Workflow: ${{ github.workflow }}"
        
        if [ -n "${{ secrets.RAILWAY_DOMAIN }}" ]; then
          echo "- Deployment URL: ${{ secrets.RAILWAY_DOMAIN }}"
          echo "✅ Railway integration configured"
        else
          echo "⚠️ Railway integration not configured"
          echo "Add RAILWAY_DOMAIN, RAILWAY_TOKEN, and RAILWAY_SERVICE_ID to secrets"
        fi

    - name: Validate GitHub Sync status
      run: |
        echo "🔄 GitHub Sync Status Check"
        echo "=============================="
        
        # Check if all required workflows exist
        WORKFLOWS=(
          ".github/workflows/ci.yml"
          ".github/workflows/deploy.yml"
          ".github/workflows/quality.yml"
          ".github/workflows/test.yml"
          ".github/workflows/dependencies.yml"
        )
        
        echo "📂 Checking workflow files:"
        for workflow in "${WORKFLOWS[@]}"; do
          if [ -f "$workflow" ]; then
            echo "✅ $workflow"
          else
            echo "❌ $workflow (missing)"
          fi
        done
        
        echo ""
        echo "🎯 GitHub Sync Implementation Complete!"
        echo "All CI/CD workflows are configured and active."